//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDiagnostics.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QueueMonitorDbEntities : DbContext
    {
        public QueueMonitorDbEntities()
            : base("name=QueueMonitorDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<TaskMessage> TaskMessages { get; set; }
        public virtual IDbSet<User> Users { get; set; }
        public virtual IDbSet<Example> Examples { get; set; }
    
        public virtual int GenerateSpecialisedPK(string sTableName, ObjectParameter sID)
        {
            var sTableNameParameter = sTableName != null ?
                new ObjectParameter("sTableName", sTableName) :
                new ObjectParameter("sTableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateSpecialisedPK", sTableNameParameter, sID);
        }
    
        public virtual ObjectResult<UpdateMessageDates_Result> UpdateMessageDates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateMessageDates_Result>("UpdateMessageDates");
        }
    }
}
