//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDiagnostics.Domain
{
    using System;
    using System.Collections.Generic;
    
    using WebDiagnostics.Domain.Attributes;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("TaskMessage")]
    public partial class TaskMessage
    {
        public System.Guid TaskMessageId { get; set; }
        public string MessageContent { get; set; }
        public int UserId { get; set; }
        public bool Success { get; set; }
        public System.DateTime MessageDate { get; set; }
        public string ExceptionDetail { get; set; }
    
        public virtual User User { get; set; }
    }
}
