//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDiagnostics.Domain
{
    using System;
    using System.Collections.Generic;
    
    using WebDiagnostics.Domain.Attributes;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("User")]
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.TaskMessages = new HashSet<TaskMessage>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string UserLoginId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskMessage> TaskMessages { get; set; }
    }
}
